 include: https://gitlab.com/telyn/ps2-cunit-port/-/raw/master/gitlab-ci-template.yml

 stages:
   - build
   - test

 build:
   image: ps2dev/ps2dev
   stage: build
   script:
     - apk add -u wget make autoconf automake bash
     - wget -O $PS2DEV/iop/lib/libps2run.a https://github.com/telyn/ps2runner/releases/latest/download/libps2run.a
     - ./install-cunit.sh
     - make
     - make -C test ee-test.elf iop-test.elf
   artifacts:
     paths:
       - ee/libcunit.a
       - iop/libcunit.a
       - test/ee-test.elf
       - test/iop-test.elf
 test-ee:
   extends: .ps2run
   stage: test
   script:
     - ps2run --ee ee-test.elf
   dependencies:
     - build
   variables:
      PS2HOSTNAME: 192.168.66.73
test-iop:
  extends: .ps2run
  stage: test
  script:
    - ps2run --iop alloc.irx
    - ps2run --iop ee-test.elf
  dependencies:
     - build
  variables:
     PS2HOSTNAME: 192.168.66.73
