include: https://gitlab.com/telyn/ps2-cunit-port/-/raw/master/gitlab-ci-template.yml

stages:
  - build
  - test

build:
  image: telyn/ps2dev
  stage: build
  script:
    - wget -O $PS2DEV/ee/lib/libps2run.a https://github.com/telyn/ps2runner/releases/latest/download/libps2run.a
    - ./install-cunit.sh
    - make
    - make -C test ee-test.elf iop-test.elf
    - cp $PS2DEV/ee/lib/libcunit.a ee/libcunit.a
  artifacts:
    paths:
      - ee/libcunit.a
      - iop/libcunit.a
      - test/ee-test.elf
      - test/iop-test.elf

test-ee:
  extends: .ps2run
  stage: test
  script:
    - ps2run --ee ee-test.elf
  dependencies:
    - build
  variables:
     PS2HOSTNAME: 192.168.66.73
  needs:
    - job: build
      artifacts: true

test-iop:
  extends: .ps2run
  stage: test
  script:
    - ps2run --iop alloc.irx
    - ps2run --iop ee-test.elf
  dependencies:
     - build
  variables:
    PS2HOSTNAME: 192.168.66.73
    GIT_STRATEGY: none
  needs:
    - job: build
      artifacts: true
